services:
  - type: web
    name: truthbot
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
    healthCheckPath: /api/health
    plan: starter

